### ISSUE TITLE
Is this endpoint correct?

### ISSUE THREAD

**Issue by aoki-h-jp** [dineshpinto/coinglass-api#1]
I think the endpoint of this method is liquidation_pair.
https://github.com/dineshpinto/coinglass-api/blob/d78d8402668fea34e9f5f5782989eb9d60b159c4/coinglass_api/api.py#L253

**Comment by dineshpinto** [comment]
Thanks for reporting this, fixed in the latest commit https://github.com/dineshpinto/coinglass-api/commit/025bbe2a70bf65f42c0861afbdd8975edefa0843
