### ISSUE TITLE
incorrect time col name

### ISSUE THREAD

**Issue by CharlesFr** [dineshpinto/coinglass-api#2]
I believe `time_col` should be `createTime` here:

https://github.com/dineshpinto/coinglass-api/blob/3d1e6f4cb166ffe77026bbc219acf67289651719/coinglass_api/api.py#L718

ps: Thanks for sharing this lib

**Comment by dineshpinto** [comment]
Hi, so coinglass has placed most of the API behind a paywall so I can't really test this anymore.
I would suggest calling `CoinglassAPI._get()` directly and then calling `CoinglassAPI._create_dataframe()` on the output.
